[package]
name = "gallerie"
version = "0.1.0"

[dependencies]
starknet = { version = "2.4.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }

[[target.starknet-contract]]
sierra = true
casm = true
[scripts]
test = "snforge test"


[sncast]
account = "argentaccount"
network = "sepolia"
rpc_url = "https://starknet-sepolia.public.blastapi.io"


[sncast_sepolia]
url = "https://starknet-sepolia.public.blastapi.io"
account = "argentaccount"
